name: my_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  adaptive_theme: ^3.7.0
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  pinput: ^5.0.1
  smart_auth: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  easy_stepper: ^0.8.5+1
  carousel_slider: ^5.0.0
  awesome_dialog: ^3.2.1
  uuid: ^4.5.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  google_maps_flutter: ^2.12.3
  get_it: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/Vector.png
    color: "#AFC7F1"
    icon_background_color: "#ffffff"
    branding: assets/images/logo.png

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
